mkdir: cannot create directory ‘/home/trihard8/repo/projects/stocks/data/20200901’: File exists
Traceback (most recent call last):
  File "/home/trihard8/repo/projects/stocks/src/fidelity_login.py", line 54, in <module>
    driver = webdriver.Chrome()
  File "/home/trihard8/repo/projects/stocks/fidelity/lib64/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/trihard8/repo/projects/stocks/fidelity/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/trihard8/repo/projects/stocks/fidelity/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/trihard8/repo/projects/stocks/fidelity/lib64/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/trihard8/repo/projects/stocks/fidelity/lib64/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

